Upgrade operator to 0.99.0
open-telemetry/opentelemetry-helm-charts pull request #1176
Opened 2024-05-08 13:18 UTC by swiatekm-sumo

Resolves #1167, alternative to #1164. 

Includes #1175, you can look at that PR if you want to see only the CRD move.

2024-05-08 17:06 UTC, pavolloffay approved these changes

2024-05-08 19:37 UTC, swiatekm-sumo commented
Please don't merge this before #1175. We've decided to do a separate release with just the CRD transition, and then the upgrade to operator 0.99.0.

2024-05-10 15:13 UTC, TylerHelmuth commented
> I'd like to change this in a follow up, probably by moving the webhooks to conf/webhooks and then including them the same way I did for CRDs, but that's up for discussion.

Agreed, created https://github.com/open-telemetry/opentelemetry-helm-charts/issues/1181

2024-05-10 15:15 UTC, TylerHelmuth approved these changes

2024-05-10 17:02 UTC, jaronoff97 approved these changes
What's the best way to ensure that users see the documentation in the Upgrading.md? I am just assuming there will be users that won't know to look there and would love to call out those instructions really clearly.

2024-05-10 17:30 UTC, jvoravong commented
> What's the best way to ensure that users see the documentation in the Upgrading.md? I am just assuming there will be users that won't know to look there and would love to call out those instructions really clearly.

I might suggest adding a smaller note in CHANGLOG.md that reference the full note in UPGRADING.md.

2024-05-10 17:36 UTC, TylerHelmuth commented
We don't have changelog files since each commit is a release - I will manually update the release notes with instructions.

2024-05-11 01:16 UTC, JaredTan95 approved these changes

2024-05-11 09:07 UTC, Allex1 approved these changes

2024-05-13 14:53 UTC, TylerHelmuth requested changes
Need https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1183 first

2024-05-13 15:33 UTC, TylerHelmuth reviewed
Once we have the docs update we'll be good to go

2024-05-13 15:52 UTC, TylerHelmuth commented on charts/opentelemetry-operator/README.md
> +> Version 0.58.0 of this Chart includes a new version of the `OpenTelemetryCollector` CRD. See [this document][v1beta1_migration] for upgrade instructions. Please make sure you also follow the [upgra
```suggestion
> Version 0.58.0 of this Chart includes a new version of the `OpenTelemetryCollector` CRD. See [this document][v1beta1_migration] for upgrade instructions for the new Operator CRD. Please make sure you also follow the [helm upgrade instructions](./UPGRADING.md#0560-to-0570) for helm chart 0.57.0.
```

2024-05-13 15:55 UTC, TylerHelmuth commented on charts/opentelemetry-operator/UPGRADING.md
> +OpenTelemetry Operator [0.99.0](https://github.com/open-telemetry/opentelemetry-operator/releases/tag/v0.99.0) includes a new version of the `OpenTelemetryCollector` CRD. See [this document][v1beta1_
```suggestion
OpenTelemetry Operator [0.99.0](https://github.com/open-telemetry/opentelemetry-operator/releases/tag/v0.99.0) includes a new version of the `OpenTelemetryCollector` CRD. See [this document][v1beta1_migration] for upgrade instructions for the new Operator CRD. Please make sure you also follow the [helm upgrade instructions](./UPGRADING.md#0560-to-0570) for helm chart 0.57.0.
```

2024-05-13 16:36 UTC, merged