[opentelemetry-operator] add timeoutSeconds and selector values for admission webhooks
open-telemetry/opentelemetry-helm-charts pull request #399
Opened 2022-10-04 14:05 UTC by Sadzeih

We have had the needs to change those values ourselves, so I figured I would make a PR for this

2022-10-04 20:50 UTC, Allex1 commented
@Sadzeih pls sign the cla and bunp the chart version.

2022-10-04 20:50 UTC, Allex1 requested changes

2022-10-04 20:50 UTC, Allex1 commented on charts/opentelemetry-operator/values.yaml
> +  # namespaceSelector: {}
@Sadzeih pls uncomment these 2 empty values and provide commented examples of both.

2022-10-04 20:53 UTC, Allex1 commented
@Sadzeih also please update title and commit message to `[opentelemetry-operator]`

2022-10-12 21:57 UTC, dmitryax approved these changes

2022-10-13 15:41 UTC, Allex1 approved these changes

2022-10-13 16:39 UTC, TylerHelmuth approved these changes

2022-10-13 16:39 UTC, merged