fix kube rbac proxy start error (#547)
open-telemetry/opentelemetry-helm-charts pull request #548
Opened 2022-12-08 10:02 UTC by ethan256

@Allex1  The /home/nonroot directory gets created with 0700 permissions, which [means](http://www.filepermissions.com/file-permission/0700) that the owning user (nonroot) has Read, Write, and Execute permissions on the directory, but other users, even those in the same group, have no permissions. In order to chdir, the calling process must have Execute permissions on the target directory.The /home/nonroot directory gets created with 0700 permissions, which [means](http://www.filepermissions.com/file-permission/0700) that the owning user (nonroot) has Read, Write, and Execute permissions on the directory, but other users, even those in the same group, have no permissions. In order to chdir, the calling process must have Execute permissions on the target directory. For more information, please refer to [CHDIR TO CWD: PERMISSION DENIED](https://danielmangum.com/posts/runc-chdir-to-cwd/)

Therefore, it works fine with the following configuration
```shell
securityContext:
  runAsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532
  fsGroup: 65532
```

2022-12-13 08:12 UTC, Allex1 commented
@ethan256 you need to bump the chart , `make generate-examples` in order for the CI to pass

2022-12-14 03:18 UTC, JaredTan95 approved these changes
LGTM

2022-12-14 06:48 UTC, Allex1 commented
@ethan256 this looks good but you still need to bump the operator chart to 0.20.3 and omit/discard the opentelemetry-demo rendered files as I think they are leftovers from a different pr. cc @puckpuck

2022-12-14 07:44 UTC, JaredTan95 commented
yes, I didn't seen you re-rendered `opentelemetry-demo` example files.

2022-12-14 13:58 UTC, puckpuck commented on Makefile
> +CHARTS ?= opentelemetry-collector opentelemetry-operator
Why is `opentelemetry-demo` removed from this list?

2022-12-15 01:58 UTC, JaredTan95 commented
@ethan256 hi, you can ref my PR's changes https://github.com/open-telemetry/opentelemetry-helm-charts/pull/563

2022-12-15 05:34 UTC, JaredTan95 requested changes

2022-12-15 05:34 UTC, JaredTan95 commented on charts/opentelemetry-collector/Chart.yaml
> +version: 0.43.2
As other PR merged, you need to bump up again. :-P

2022-12-15 06:38 UTC, JaredTan95 commented
and the last thing, pls resolve conflicts.

2022-12-15 08:41 UTC, Allex1 commented on charts/opentelemetry-demo/Chart.yaml
> +version: 0.15.2
this is unnecessary

2022-12-15 08:42 UTC, Allex1 commented on charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
>      helm.sh/chart: opentelemetry-operator-0.20.3
only `helm.sh/chart: opentelemetry-operator-0.20.4` should be here

2022-12-15 15:15 UTC, Allex1 approved these changes

2022-12-15 15:58 UTC, TylerHelmuth approved these changes

2022-12-15 15:58 UTC, merged